### ISSUE TITLE
register the package

### ISSUE THREAD

**Issue by Roger-luo** [GiggleLiu/BackwardsLinalg.jl#6]
You need to add me as collaborator, so I will have the access.

**Comment by GiggleLiu** [comment]
You are already a collaborator, don’t you have access?

**Comment by Roger-luo** [comment]
I don't think so. It seems that I can't add the bot for you. Or can you transfer the repo to QuantumBFS? Everything will be kept, and I'll have access.

**Comment by GiggleLiu** [comment]
No need to bother, I will figure out, thanks.

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register branch=master

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
You need to add it to your account

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register branch=master

**Comment by Roger-luo** [comment]
And remember to install TagBot.

**Comment by Roger-luo** [comment]
The default branch is master, just write register is fine.

**Comment by GiggleLiu** [comment]
Thanks, done.

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register
